FROM node:12.16.3

WORKDIR /frontend

RUN npm install && \
    npm install -g @vue/cli && \
    npm install -g @vue/cli-init && \
    npm install -g @nuxtjs/axios && \
    npm install -g @nuxtjs/auth && \
    npm install -g @nuxtjs/dotenv

RUN npm build

ADD . .

RUN npm install

ENV HOST 0.0.0.0
EXPOSE 8080
