FROM node:12.16.3-alpine

WORKDIR /frontend/

RUN apk update && \
    npm install -g @vue/cli && \
    npm install -g @vue/cli-init && \
    npm install -g @nuxtjs/axios && \
    npm install -g @nuxtjs/auth && \
    npm install -g @nuxtjs/dotenv

ADD ./frontend/ .

RUN npm install
RUN npm run build

ENV BASE_URL http://poeta-lb-1208516177.ap-northeast-1.elb.amazonaws.com

ENV HOST 0.0.0.0
EXPOSE 3000
