FROM node:12.16.3-alpine

WORKDIR /frontend

RUN apk update && \
    npm install -g @vue/cli && \
    npm install -g @vue/cli-init && \
    npm install -g @nuxtjs/axios && \
    npm install -g @nuxtjs/auth && \
    npm install -g @nuxtjs/dotenv

ADD . .

RUN npm install
RUN npm run build

ENV BASE_URL http://34.85.15.10
ENV CLIENT_URL http://35.221.110.39

ENV HOST 0.0.0.0
EXPOSE 3000
