version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  api:
    build: .
    image: asia.gcr.io/poeta-276706/poeta-api:latest
    depends_on:
      - db
    # 初回コンテナ起動時のみコメントインする（それ以外の時はコメントアウト）
    # entrypoint: ./wait-for-it.sh db:3306
    # entrypointコメントイン時のみコメントアウトする（通常は基本コメントインしておく）
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/languageMemoApp
    ports:
      - "3000:3000"
    tty: true
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"

  front:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: asia.gcr.io/poeta-276706/poeta-front:latest
    command: npm run dev
    ports:
      - 3001:3000
    depends_on:
      - api
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/frontend

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
