version: "3"
services:
  api:
    build: .
    command: bundle exec rails s
    volumes:
      - .:/languageMemoApp
    ports:
      - "3000:3000"
    tty: true
    environment:
      RAILS_ENV: production
      # DB_HOST: RDS_DNS
      # DB_USERNAME: username
      # DB_PASSWORD: password
      # DB_DATABASE: databasename

  front:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: nuxt start
    ports:
      - 3001:3000
    depends_on:
      - api
    volumes:
      - .:/frontend
