version: "3"
services:
  api:
    build: .
    image: asia.gcr.io/poeta-276706/poeta-api:latest
    volumes:
      - .:/languageMemoApp
    ports:
      - "3000:3000"

  front:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: asia.gcr.io/poeta-276706/poeta-front:latest
    ports:
      - 3001:3000
