version: "3"
services:
  api:
    build: .
    image: asia.gcr.io/poeta-276706/poeta-api:latest
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/languageMemoApp
    ports:
      - "3000:3000"
    tty: true

  front:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: asia.gcr.io/poeta-276706/poeta-api:latest
    command: npm run dev
    ports:
      - 3001:3000
    depends_on:
      - api
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/frontend
