version: "3"
services:
  api:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/languageMemoApp
    ports:
      - "3000:3000"
    tty: true
    environment:
      RAILS_ENV: production
      # DB_HOST: ◯◯.△△.ap-northeast-1.rds.amazonaws.com
      # DB_USERNAME: ユーザー名
      # DB_PASSWORD: パスワード
      # DB_DATABASE: データベース名

  front:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm run dev
    ports:
      - 3001:3000
    depends_on:
      - api
    tty: true
    stdin_open: true
    # Hot Module Replacement (HMR) is enable for virtual box.
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/frontend
