version: "3"
services:
  api:
    build: .
    image: 139465735782.dkr.ecr.ap-northeast-1.amazonaws.com/poeta-api
    volumes:
      - .:/languageMemoApp
    ports:
      - "3000:3000"

  front:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    image: 139465735782.dkr.ecr.ap-northeast-1.amazonaws.com/poeta-front
    ports:
      - 3001:3000
