version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
executors:
  builder:
    docker:
      - image: circleci/buildpack-deps

commands:
  init:
    steps:
      - checkout
      - aws-cli/install
      - install_ecs-cli
      - setup_remote_docker
  install_ecs-cli:
    steps:
      - run:
          name: Install ECS-CLI
          command: |
            sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
            sudo chmod +x /usr/local/bin/ecs-cli

jobs:
  build:
    executor: builder
    steps:
      - init
      - run:
          name: Build application Docker image
          command: |
            docker build -f Dockerfile --rm=false -t 139465735782.dkr.ecr.ap-northeast-1.amazonaws.com/poeta-api .
      - run:
          name: Save image
          command: |
            mkdir -p /tmp/docker
            docker save 139465735782.dkr.ecr.ap-northeast-1.amazonaws.com/poeta-api -o /tmp/docker/image
      - persist_to_workspace:
          root: /tmp/docker
          paths:
            - image
  deploy:
    executor: builder
    steps:
      - init
      - attach_workspace:
          at: /tmp/docker
      - run: docker load -i /tmp/docker/image
      - run:
          name: Assets precompile and Push Docker image
          command: |
            docker build -f Dockerfile --build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY} --rm=false -t 139465735782.dkr.ecr.ap-northeast-1.amazonaws.com/poeta-api .
      - run:
          name: Push Docker image
          command: |
            ecs-cli push 139465735782.dkr.ecr.ap-northeast-1.amazonaws.com/poeta-api
      - run:
          name: ECS Config
          command: |
            ecs-cli configure \
            --cluster poeta-cluster-${CIRCLE_BRANCH} \
            --region ${AWS_DEFAULT_REGION} \
            --config-name poeta-${CIRCLE_BRANCH}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
