version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/languageMemoApp
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose stop
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up -d
      - run:
          name: bundle Install
          command: |
            set -x
            docker-compose exec api bin/bundle install --path=vendor/bundle
      - run:
          name: rspec
          command: |
            set -x
            docker-compose exec api rspec
      - run:
          name: rubocop
          command: |
            set -x
            docker-compose exec api rubocop
    working_directory: ~/languageMemoApp/frontend
      - run:
          name: jest
          command: |
            set -x
            docker-compose exec front npm test
      - run:
          name: lint
          command: |
            set -x
            docker-compose exec front npm run lintfix
      - run:
          name: docker-compose down
          command: docker-compose down